// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Nty9d9heTwBRioAAvz2UZv2SdmYIIo4',
    appId: '1:1017058131677:web:069447895347e74f4fe534',
    messagingSenderId: '1017058131677',
    projectId: 'wells-app-614df',
    authDomain: 'wells-app-614df.firebaseapp.com',
    storageBucket: 'wells-app-614df.appspot.com',
    measurementId: 'G-WMMYB226PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP2yWIn3zjcHkXajbUI6UZjy-TPLFR2OE',
    appId: '1:1017058131677:android:ae4f33bfc3b1a54d4fe534',
    messagingSenderId: '1017058131677',
    projectId: 'wells-app-614df',
    storageBucket: 'wells-app-614df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX3NJez8bR-YIr9u1jZxRBEfJBt-490dw',
    appId: '1:1017058131677:ios:1241e001e85fd6c34fe534',
    messagingSenderId: '1017058131677',
    projectId: 'wells-app-614df',
    storageBucket: 'wells-app-614df.appspot.com',
    iosBundleId: 'com.example.wells',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX3NJez8bR-YIr9u1jZxRBEfJBt-490dw',
    appId: '1:1017058131677:ios:0b434a3040048efe4fe534',
    messagingSenderId: '1017058131677',
    projectId: 'wells-app-614df',
    storageBucket: 'wells-app-614df.appspot.com',
    iosBundleId: 'com.example.wells.RunnerTests',
  );
}
